export interface Product {
  id: string;
  name: string;
  nameTh: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  code: string;
  description: string;
  descriptionTh: string;
  rating: number;
  reviews: number;
  badge?: string;
  inStock: boolean;
}

export const products: Product[] = [
  {
    id: "1",
    name: "Nutrilite Double X",
    nameTh: "นิวทริไลท์ ดับเบิ้ล เอ็กซ์",
    price: 2890,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop",
    category: "health",
    code: "NTX-001",
    badge: "Best Seller",
    description: "Multivitamin supplement with 22 plant concentrates",
    descriptionTh: "อาหารเสริมวิตามินรวมจากสารสกัดพืช 22 ชนิด",
    rating: 4.8,
    reviews: 245,
    inStock: true,
  },
  {
    id: "2",
    name: "Artistry Skin Nutrition",
    nameTh: "อาร์ทิสทรี สกิน นิวทริชั่น",
    price: 1950,
    originalPrice: 2300,
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop",
    category: "beauty",
    code: "ART-002",
    badge: "New",
    description: "Premium skincare cream with plant-based nutrients",
    descriptionTh: "ครีมบำรุงผิวพรีเมียมจากสารอาหารจากพืช",
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  {
    id: "3",
    name: "eSpring Water Purifier",
    nameTh: "อีสปริง เครื่องกรองน้ำ",
    price: 28900,
    originalPrice: 32000,
    image: "https://i.pinimg.com/736x/36/c6/e4/36c6e4217ae5c8a57f29404cc7d8873e.jpg",
    category: "tech",
    code: "ESP-003",
    description: "UV water treatment system for clean drinking water",
    descriptionTh: "ระบบกรองน้ำด้วย UV สำหรับน้ำดื่มสะอาด",
    rating: 4.9,
    reviews: 312,
    inStock: true,
  },
  {
    id: "4",
    name: "Atmosphere Air Purifier",
    nameTh: "แอทโมสเฟียร์ เครื่องฟอกอากาศ",
    price: 35900,
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop",
    category: "tech",
    code: "ATM-004",
    badge: "Premium",
    description: "HEPA air filtration system for home and office",
    descriptionTh: "ระบบกรองอากาศ HEPA สำหรับบ้านและออฟฟิศ",
    rating: 4.7,
    reviews: 156,
    inStock: true,
  },
  {
    id: "5",
    name: "XS Energy Drink",
    nameTh: "เอ็กซ์เอส เครื่องดื่มให้พลังงาน",
    price: 69,
    image: "https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=400&h=400&fit=crop",
    category: "lifestyle",
    code: "XSE-005",
    description: "Sugar-free energy drink with B vitamins",
    descriptionTh: "เครื่องดื่มให้พลังงานไม่มีน้ำตาลเสริมวิตามินบี",
    rating: 4.3,
    reviews: 567,
    inStock: true,
  },
  {
    id: "6",
    name: "Glister Toothpaste",
    nameTh: "กลิสเทอร์ ยาสีฟัน",
    price: 290,
    originalPrice: 350,
    image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=400&h=400&fit=crop",
    category: "lifestyle",
    code: "GLT-006",
    badge: "Sale",
    description: "Multi-action fluoride toothpaste",
    descriptionTh: "ยาสีฟันฟลูออไรด์สูตรมัลติแอคชั่น",
    rating: 4.5,
    reviews: 423,
    inStock: true,
  },
  {
    id: "7",
    name: "Bodykey Meal Replacement",
    nameTh: "บอดี้คีย์ มีลรีเพลสเมนท์",
    price: 1490,
    originalPrice: 1790,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=400&fit=crop",
    category: "health",
    code: "BKY-007",
    description: "Nutritious meal replacement shake",
    descriptionTh: "เชคทดแทนมื้ออาหารเสริมสารอาหาร",
    rating: 4.4,
    reviews: 198,
    inStock: true,
  },
  {
    id: "8",
    name: "Satinique Hair Care Set",
    nameTh: "ซาทินีค ชุดดูแลผม",
    price: 1290,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=400&fit=crop",
    category: "beauty",
    code: "SAT-008",
    badge: "Popular",
    description: "Professional hair care with botanical ingredients",
    descriptionTh: "ชุดดูแลผมมืออาชีพจากสารสกัดธรรมชาติ",
    rating: 4.6,
    reviews: 276,
    inStock: true,
  },
  {
    id: "9",
    name: "Satinique Repair Shampoo",
    nameTh: "ซาทินีค แชมพูซ่อมแซมผม",
    price: 690,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop",
    category: "beauty",
    code: "SAT-009",
    badge: "Hot",
    description: "Repair damaged hair and restore natural shine",
    descriptionTh: "ฟื้นฟูผมเสียและคืนความเงางามตามธรรมชาติ",
    rating: 4.7,
    reviews: 198,
    inStock: true,
  },
  {
    id: "10",
    name: "Satinique Shampoo",
    nameTh: "ซาทินีค แชมพู",
    price: 650,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop",
    category: "beauty",
    code: "SAT-010",
    badge: "New",
    description: "Gentle cleansing shampoo",
    descriptionTh: "แชมพูทำความสะอาดอย่างอ่อนโยน",
    rating: 4.5,
    reviews: 190,
    inStock: true,
  },
  {
    id: "11",
    name: "Satinique Conditioner",
    nameTh: "ซาทินีค ครีมนวดผม",
    price: 690,
    image: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=400&h=400&fit=crop",
    category: "beauty",
    code: "SAT-011",
    badge: "Hot",
    description: "Smooth and soft hair conditioner",
    descriptionTh: "ครีมนวดผมให้ผมนุ่มลื่น",
    rating: 4.7,
    reviews: 210,
    inStock: true,
  },
  {
    id: "12",
    name: "Satinique Hair Treatment",
    nameTh: "ซาทินีค ทรีทเมนต์ผม",
    price: 850,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400&h=400&fit=crop",
    category: "beauty",
    code: "SAT-012",
    badge: "Popular",
    description: "Deep hair repair treatment",
    descriptionTh: "ทรีทเมนต์ฟื้นฟูเส้นผมล้ำลึก",
    rating: 4.8,
    reviews: 300,
    inStock: true,
  },
  {
    id: "13",
    name: "Satinique Hair Serum",
    nameTh: "ซาทินีค เซรั่มผม",
    price: 720,
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop",
    category: "beauty",
    code: "SAT-013",
    badge: "New",
    description: "Hair serum for shine and protection",
    descriptionTh: "เซรั่มผมเพิ่มความเงางาม",
    rating: 4.6,
    reviews: 165,
    inStock: true,
  },
  {
    id: "14",
    name: "Satinique Scalp Tonic",
    nameTh: "ซาทินีค โทนิคบำรุงหนังศีรษะ",
    price: 790,
    image: "https://www.amway.com/medias/126466-en-US-690px-03?context=bWFzdGVyfGltYWdlc3wzNTQ2NDN8aW1hZ2UvcG5nfHN5cy1tYXN0ZXIvaW1hZ2VzL2gyMC9oMWQvOTk1Mzk5MTUyNDM4Mi8xMjY0NjYtZW4tVVMtNjkwcHgtMDN8NGFlZTYzMjRmZWNiNjc5MzI1Y2QzZTE2Y2RlM2QzZmQwNjBkMjJmYTg3NjllNjAzM2VlMjY3YmNiMjg4Zjk2Zg",
    category: "beauty",
    code: "SAT-014",
    badge: "Hot",
    description: "Scalp care tonic",
    descriptionTh: "โทนิคดูแลหนังศีรษะ",
    rating: 4.5,
    reviews: 140,
    inStock: true,
  },
  {
    id: "15",
    name: "Satinique Hair Mask",
    nameTh: "ซาทินีค มาส์กผม",
    price: 900,
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400&h=400&fit=crop",
    category: "beauty",
    code: "SAT-015",
    badge: "Popular",
    description: "Hair mask for deep nourishment",
    descriptionTh: "มาส์กผมบำรุงล้ำลึก",
    rating: 4.7,
    reviews: 220,
    inStock: true,
  },
  {
    id: "16",
    name: "Satinique Hair Spray",
    nameTh: "ซาทินีค สเปรย์ผม",
    price: 620,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop",
    category: "beauty",
    code: "SAT-016",
    badge: "New",
    description: "Hair styling spray",
    descriptionTh: "สเปรย์จัดแต่งทรงผม",
    rating: 4.4,
    reviews: 120,
    inStock: true,
  },
];

export const promotions = [
  {
    id: "p1",
    title: "New Member Special",
    titleTh: "โปรสมาชิกใหม่",
    discount: 15,
    code: "NEWUSER15",
    description: "Get 15% off your first order",
    descriptionTh: "รับส่วนลด 15% สำหรับคำสั่งซื้อแรก",
    color: "from-primary to-secondary",
  },
  {
    id: "p2",
    title: "Amway Exclusive",
    titleTh: "แอมเวย์ เอ็กซ์คลูซีฟ",
    discount: 20,
    code: "AMWAY20",
    description: "20% off all Amway products",
    descriptionTh: "ลด 20% สินค้าแอมเวย์ทุกชิ้น",
    color: "from-secondary to-accent",
  },
  {
    id: "p3",
    title: "Shop & Save",
    titleTh: "ช้อป & ประหยัด",
    discount: 50,
    code: "SHOP50",
    description: "฿50 off orders over ฿1,000",
    descriptionTh: "ลด ฿50 เมื่อช้อปครบ ฿1,000",
    color: "from-accent to-primary",
  },
];

export const categories = [
  { id: "health", icon: "health", label: "Health", labelTh: "สุขภาพ", count: 24 },
  { id: "beauty", icon: "beauty", label: "Beauty", labelTh: "ความงาม", count: 18 },
  { id: "lifestyle", icon: "lifestyle", label: "Lifestyle", labelTh: "ไลฟ์สไตล์", count: 15 },
  { id: "tech", icon: "tech", label: "Tech", labelTh: "เทคโนโลยี", count: 8 },
  { id: "partner", icon: "partner", label: "Partner", labelTh: "พาร์ทเนอร์", count: 32 },
];

export const partners = [
  {
    id: "amway",
    name: "Amway",
    logo: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=200&h=200&fit=crop",
    description: "Global leader in health and beauty products",
    descriptionTh: "ผู้นำระดับโลกด้านผลิตภัณฑ์สุขภาพและความงาม",
    active: true,
  },
  {
    id: "partner2",
    name: "Coming Soon",
    logo: "",
    description: "New partner coming soon",
    descriptionTh: "พาร์ทเนอร์ใหม่เร็วๆ นี้",
    active: false,
  },
  {
    id: "partner3",
    name: "Coming Soon",
    logo: "",
    description: "New partner coming soon",
    descriptionTh: "พาร์ทเนอร์ใหม่เร็วๆ นี้",
    active: false,
  },
];

export const videos = [
  {
    id: "v1",
    title: "Product Review",
    titleTh: "รีวิวสินค้า",
    platform: "TikTok",
    thumbnail: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=300&fit=crop",
    url: "#",
  },
  {
    id: "v2",
    title: "Unboxing Haul",
    titleTh: "แกะกล่องสินค้า",
    platform: "Instagram",
    thumbnail: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=300&fit=crop",
    url: "#",
  },
  {
    id: "v3",
    title: "How to Use Guide",
    titleTh: "วิธีใช้งาน",
    platform: "YouTube",
    thumbnail: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&h=300&fit=crop",
    url: "#",
  },
];
