-- =============================================================================
-- 0016 — Automatic display codes
-- =============================================================================
-- PRJ-2026-001, CR-2026-004 and friends are generated by app.next_code(), which
-- lives in the `app` schema and is therefore NOT reachable through PostgREST.
-- That is deliberate (migration 0001), but it leaves the application unable to
-- ask for a code when inserting a row.
--
-- The answer is a trigger rather than an exposed RPC:
--
--   * The application never handles a code at all, so it cannot pass a
--     duplicate, a forged one, or one belonging to another organization.
--   * Numbering is atomic with the insert. Two concurrent project creations
--     cannot both read "last was 007" and both write 008 — app.next_code()
--     increments inside the same transaction.
--   * A direct SQL insert gets a code too, so seeds and back-fills stay
--     consistent with the application.
--
-- These codes remain DISPLAY ONLY. Guessing PRJ-2026-002 must get you nothing:
-- every URL and every policy addresses rows by UUID.
-- =============================================================================

create or replace function app.set_project_code()
returns trigger
language plpgsql
security definer
set search_path = public, app, pg_temp
as $$
begin
  if new.project_code is null or length(btrim(new.project_code)) = 0 then
    new.project_code := app.next_code(new.organization_id, 'PRJ');
  end if;
  return new;
end;
$$;

-- BEFORE INSERT, so the generated value satisfies the NOT NULL constraint:
-- constraints are checked after BEFORE triggers have run.
create trigger projects_set_code
  before insert on projects
  for each row execute function app.set_project_code();

create or replace function app.set_change_request_code()
returns trigger
language plpgsql
security definer
set search_path = public, app, pg_temp
as $$
declare
  v_org uuid;
begin
  if new.request_code is null or length(btrim(new.request_code)) = 0 then
    -- change_requests hangs off a project, so the organization is one hop away.
    select organization_id into v_org from projects where id = new.project_id;
    if v_org is not null then
      new.request_code := app.next_code(v_org, 'CR');
    end if;
  end if;
  return new;
end;
$$;

create trigger change_requests_set_code
  before insert on change_requests
  for each row execute function app.set_change_request_code();

-- =============================================================================
-- public.log_activity — the audit writer the application can actually reach
-- =============================================================================
-- app.log_activity() is SECURITY DEFINER and fills the actor from the session,
-- but it lives in `app` and PostgREST cannot call it. activity_logs has no
-- INSERT policy by design, so without a reachable wrapper no server action
-- could record anything.
--
-- The wrapper re-checks authorization before delegating. That check is the
-- reason it is safe to expose: app.log_activity() trusts its arguments, and a
-- caller who could pass an arbitrary organization_id would be able to write
-- entries into another tenant's audit trail. Here, you may only log against a
-- project you can read or an organization you belong to.
--
-- The actor is still taken from auth.uid() inside app.log_activity(), so an
-- action can never be attributed to someone else.
-- =============================================================================
create or replace function public.log_activity(
  p_organization_id uuid,
  p_action          text,
  p_entity_type     text,
  p_entity_id       uuid  default null,
  p_project_id      uuid  default null,
  p_metadata        jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, app, pg_temp
as $$
begin
  if p_project_id is not null then
    if not app.can_read_project(p_project_id) then
      raise exception 'not authorized to log activity for this project'
        using errcode = '42501';
    end if;
  elsif not app.is_org_member(p_organization_id) then
    raise exception 'not authorized to log activity for this organization'
      using errcode = '42501';
  end if;

  return app.log_activity(
    p_organization_id,
    p_action,
    p_entity_type,
    p_entity_id,
    p_project_id,
    p_metadata
  );
end;
$$;

revoke all on function public.log_activity(uuid, text, text, uuid, uuid, jsonb) from public;
grant execute on function public.log_activity(uuid, text, text, uuid, uuid, jsonb) to authenticated;
